DROP TABLE IF EXISTS `pocbase`.`acteur`;

CREATE TABLE  `pocbase`.`acteur` (
  `IDENTIFIANT` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NOM` varchar(100) NOT NULL,
  `PRENOM` varchar(100) NOT NULL,
  PRIMARY KEY (`IDENTIFIANT`) USING BTREE,
  UNIQUE KEY `UNI_NOM` (`NOM`),
  UNIQUE KEY `UNI_IDENTIFIANT` (`IDENTIFIANT`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;